### ISSUE TITLE
series date leeg, geen datum in dropdown

### ISSUE THREAD

**Issue by JaapGroen** [wadqc/WAD_Services#12]

**Comment by tcdewit** [comment]
Dcm4chee slaat helaas geen seriestime op; in plaats daarvan wordt de content_time van de eerste instance gebruikt om te tonen in de dropdown. Blijkbaar wordt deze dus niet altijd gevuld.
De query in show_results.php zal moeten worden aangepast om terug te vallen op studytime, mits content_time leeg is, dus bijv (ongetest):

$year_Stmt_series="SELECT $table_gewenste_processen.pk as 'pk', $table_gewenste_processen.status as 'status', coalesce($table_instance.content_datetime,$table_study.study_datetime) as 'date_time' from $table_gewenste_processen inner join $table_series on $table_gewenste_processen.series_fk=$table_series.pk, $table_instance, $table_study where $table_gewenste_processen.selector_fk=$selector_fk and $table_gewenste_processen.status in (%s) and $table_series.pk=$table_instance.series_fk and $table_instance.pk=(select min(pk) from $table_instance where series_fk=$table_series.pk) and $table_study.pk=$table_series.study_fk order by $table_instance.content_datetime desc";
