### ISSUE TITLE
lijst bij status-selector blijft eeuwig bestaan

### ISSUE THREAD

**Issue by JaapGroen** [wadqc/WAD_Services#15]
Alle ooit ingeschoten onderzoeken komen in een lijst te staan op de WADsite bij status-selector met de status "selector klaar".
Het zou mooi zijn als deze lijst op te schonen is. Helemaal mooi zou zijn als alleen onderzoeken blijven staan die niet door een selector heen komen. Of bij geen enkele selector passen.

**Comment by wadqc** [comment]
This issue was moved to wadqc/WAD_Interface#65
