### ISSUE TITLE
QC frequentie 1 keer per x dagen ipv dropdown?

### ISSUE THREAD

**Issue by JaapGroen** [wadqc/WAD_Services#17]
De keuze van de QC frequentie bij het opstellen van een selector is beperkt tot dag/week/maand/etc.

Flexibeler zou zijn om 1 keer per xx dagen, waarbij xx een int invulveld is.

**Comment by tcdewit** [comment]
allereerst: svp topic voortaan bij het juiste onderdeel aanmaken; deze hoort eigenlijk thuis bij de WAD_Interface (@Joost: zou je deze nog kunnen verhuizen?).

Configurabel maken is niet erg eenvoudig en wordt, denk ik, niet veel gebruikt straks. Veel voorkomende frequenties zijn al gedefinieerd, maar aan deze lijst kunnen uiteraard nieuwe entries worden toegevoegd. Mocht je behoefte hebben aan andere QC frequenties, dan kunnen deze worden toegevoegd in:
WAD-IQC/database/globals.php

**Comment by wadqc** [comment]
This issue was moved to wadqc/WAD_Interface#67
