### ISSUE TITLE
Problemen met selector constraints

### ISSUE THREAD

**Issue by tcdewit** [wadqc/WAD_Services#8]
Bij het toepassen van de constraints (Selector.java --> isEqualSeriesHashmaps()) wordt momenteel een match gevonden indien de selectorSeriesValue (selector-constraint op series level) **of** seriesValue (te checken entry in serie-tabel) leeg is. Dit lijkt me niet wenselijk.
Zijn jullie het er mee eens dat dit als volgt logischer is?

selectorSeriesValue leeg --> match op kolom, ongeacht waarde van seriesValue
seriesValue leeg --> alleen match als ook selectorSeriesValue leeg is.

Zelfde gaat ook op voor patient/study/instance level...

**Comment by tcdewit** [comment]
Mogelijke fix in commit b1cb29419ed8ecf78d4478951acc690c1ca0df61.

**Comment by wadqc** [comment]
Als ik het goed begrijp was er dus altijd een match indien óf het criterium veld leeg is, óf het betreffende DICOM veld leeg is (zelfs als er voor dat veld wél een criterium ingevuld was).

En dan bovenstaand voorstel, met toevoeging van mijn interpretatie:
- bij een gegeven veld is geen criterium ingevuld: selectorSeriesValue leeg --> match op kolom, ongeacht waarde van seriesValue. Dus: altijd een match want er is geen criterium ingevuld.

- als een gegeven DICOM veld leeg is: seriesValue leeg --> alleen match als ook selectorSeriesValue leeg is, dwz er geen criterium is ingevuld. Dit iit eerdere implementatie (pre b1cb29419ed8ecf78d4478951acc690c1ca0df61) waar een leeg DICOM veld altijd een match gaf, zelfs als er voor dat veld wél een criterium was ingevuld.

Lijkt me inderdaad logischer.

**Comment by tcdewit** [comment]
Je interpretatie klopt inderdaad... met de kleine aanvulling dat bovenstaande ook opging als de dicom-tag voor sommige gevallen niet bestond (bijv (0020,4000) "image comments" in een instance). Ook in zo'n geval wil je geen match als er wel een criterium is ingevuld.
Eerdergenoemde fix lijkt bij mij vooralsnog goed te werken.
